# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Social media usernames
twitter: jekyllrb
facebook: 
google-plus:
linkedin: 
dribbble: 
flickr: 
bitbucket: jekyll
github: jekyll

# Postal address
address-line1: 3481 Melrose Place
address-line2: Beverly Hills, CA 90210
address-line3:
address-line4:

# Build settings
markdown: kramdown
permalink: pretty
